# Generated by Django 4.2.30 on 2026-08-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefecture', models.CharField(choices=[('shizuoka', '静岡県'), ('aichi', '愛知県'), ('gifu', '岐阜県'), ('mie', '三重県')], max_length=20, verbose_name='都道府県')),
                ('section_number', models.IntegerField(verbose_name='区間番号')),
                ('route_name', models.CharField(max_length=100, verbose_name='路線名')),
                ('start_point', models.CharField(blank=True, default='', max_length=200, verbose_name='起点側路線名')),
                ('end_point', models.CharField(blank=True, default='', max_length=200, verbose_name='終点側路線名')),
                ('municipality_code', models.CharField(blank=True, default='', max_length=20, verbose_name='市区町村コード')),
                ('expressway_type', models.CharField(blank=True, default='', max_length=50, verbose_name='専用道路')),
                ('section_length', models.FloatField(default=0, verbose_name='区間延長(km)')),
                ('upstream_point', models.CharField(blank=True, default='', max_length=200, verbose_name='上り観測地点')),
                ('upstream_traffic', models.IntegerField(default=0, verbose_name='24h上り交通量(台)')),
                ('downstream_point', models.CharField(blank=True, default='', max_length=200, verbose_name='下り観測地点')),
                ('downstream_traffic', models.IntegerField(default=0, verbose_name='24h下り交通量(台)')),
                ('total_traffic', models.IntegerField(default=0, verbose_name='24h交通量合計(台)')),
                ('day_night_ratio', models.FloatField(default=0, verbose_name='昼夜率')),
                ('congestion_degree', models.FloatField(default=0, verbose_name='混雑度')),
                ('upstream_speed', models.FloatField(default=0, verbose_name='上り速度(km/h)')),
                ('downstream_speed', models.FloatField(default=0, verbose_name='下り速度(km/h)')),
                ('road_width', models.FloatField(default=0, verbose_name='幅員(m)')),
                ('speed_limit', models.IntegerField(default=0, verbose_name='最高速度(km/h)')),
            ],
            options={
                'ordering': ['section_number'],
                'indexes': [models.Index(fields=['prefecture', 'route_name'], name='roads_road_prefect_bc9b2e_idx'), models.Index(fields=['prefecture', 'section_length'], name='roads_road_prefect_96662d_idx')],
                'unique_together': {('prefecture', 'section_number')},
            },
        ),
    ]
